---
sudo: required
dist: trusty
language: php
php:
  - '5.6'
  - '7.0'
before_script:
  - sudo apt-get -y update
  - sudo apt-get -y install tesseract-ocr tesseract-ocr-deu tesseract-ocr-jpn tesseract-ocr-por
install:
  - composer install
script:
  - vendor/bin/phpunit
after_success:
  - bash <(curl -s https://codecov.io/bash)
